### Google sign-in
POST http://localhost:5000/auth/google
Content-Type: application/json

{
    "idToken": "your-google-id-token"
}

### Register a new user
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "email": "elor@gmail.com",
    "password": "123456",
    "firstName": "Elor",
    "lastName": "Itzkovitz"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "elor@gmail.com",
  "password": "123456"
}

### Refresh token
POST http://localhost:3000/auth/refresh
Content-Type: application/json

{

  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzgzZTRhYjVjMDU2MDUxN2U0NjllNTAiLCJyYW5kb20iOiIwLjE1ODkxMTQyNzUzNjA0NzkyIiwiaWF0IjoxNzM2Njk3MTAxLCJleHAiOjE3MzczMDE5MDF9.18uphsxcXoUcG63ADAWCbhclS2NOsIP7Maw6spGuL84"
}

### Get user data (Authenticated)
GET http://localhost:5000/auth/user
Authorization: Bearer your-access-token

### Search users by name
GET http://localhost:5000/auth/users?query=Bob
Authorization: Bearer your-access-token

### Update user data
PUT http://localhost:5000/auth/user/60d21b4667d0d8992e610c85
Content-Type: multipart/form-data
Authorization: Bearer your-access-token

{
    "firstName": "UpdatedElor",
    "lastName": "UpdatedItzkovitz",
    "password": "newpassword"
}

### Logout
POST http://localhost:3000/auth/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzgzZTRhYjVjMDU2MDUxN2U0NjllNTAiLCJyYW5kb20iOiIwLjc4MzA2Nzk2ODY4MDQwNzYiLCJpYXQiOjE3MzY2OTcxMjEsImV4cCI6MTczNzMwMTkyMX0.bmNMJADEslzsMJG3JyrU7HPvHAZ2VDVWZiPPTTngi3A"
}

### Create a New Post
POST http://localhost:3000/posts
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzgzZDM3ZmNlYTVhODYwODM5YzdiZGMiLCJyYW5kb20iOiIwLjMwMTc1Mjg4MTY4NjE2NTkiLCJpYXQiOjE3MzY2OTI2ODAsImV4cCI6MTczNjcwMzQ4MH0.pk10Z8UOVfnd5vF28vlMtXSDIS8ohRUR8cBLp2KaBG4

{ 
  "title": "First Post",
  "content": "This is my first post!",
  "sender": "67da902edf69b6d2a95a1020"
}

### Get all posts
GET http://localhost:3000/posts

### Get post by id
GET http://localhost:3000/posts/677c451bdb9d5917464523b9

### Update post
PUT http://localhost:3000/posts/677c451bdb9d5917464523b9
Content-Type: application/json

{ 
  "title": "First Post - Edited",
  "content": "This is my first post, now edited!",
  "sender": "67da902edf69b6d2a95a1020"
}

### Like/unlike post
POST http://localhost:3000/posts/677c451bdb9d5917464523b9/like
Authorization: Bearer your-access-token

### Delete post
DELETE http://localhost:3000/posts/677c451bdb9d5917464523b9

### Create a new comment
POST http://localhost:3000/comments
Content-Type: application/json

{ 
  "postId": "677c451bdb9d5917464523b9",
  "content": "This is my first comment!",
  "sender": "67da902edf69b6d2a95a1020"
}

### Get all comments
GET http://localhost:3000/comments

### Get comments by post id
GET http://localhost:3000/comments?postId=677c451bdb9d5917464523b9

### Update comment
PUT http://localhost:3000/comments/677c4d3e0b9a6dc090dd9772
Content-Type: application/json

{ 
  "postId": "677c451bdb9d5917464523b9",
  "content": "This is my first comment, edited!",
  "sender": "67da902edf69b6d2a95a1020"
}

### Like/unlike comment
POST http://localhost:3000/comments/677c4d3e0b9a6dc090dd9772/like
Authorization: Bearer your-access-token

### Delete comment
DELETE http://localhost:3000/comments/677c4d3e0b9a6dc090dd9772